# Generated by Django 5.1.6 on 2025-02-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_alter_home_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='movieapp/')),
            ],
        ),
        migrations.DeleteModel(
            name='Home',
        ),
    ]
