# Generated by Django 5.1.6 on 2025-02-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0006_movie_actors_movie_director_movie_genre_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
